import os
import pyvisa

def capture_oscilloscope_screenshot_pyvisa(visa_resource_addr, csv_file_path):
    """
    Capture a screenshot from the oscilloscope using PyVISA, using the
    metadata from csv_file_path to name the screenshot. The screenshot
    will be saved in the same directory as the CSV file.
    
    Args:
        visa_resource_addr (str): VISA address, e.g. 'TCPIP0::192.168.1.100::inst0::INSTR'
        csv_file_path (str): The full file path to the CSV generated by generate_filename.
    """
    try:
        folder_path = os.path.dirname(csv_file_path)

        # Use CSV filename (without extension) for screenshot
        base_name = os.path.basename(csv_file_path)
        base_name_no_ext = os.path.splitext(base_name)[0]
        screenshot_name = base_name_no_ext + ".png"
        screenshot_path = os.path.join(folder_path, screenshot_name)

        # Temp path on scope
        temp_on_scope = "C:/Temp.png"

        # Connect using VISA
        rm = pyvisa.ResourceManager()
        scope = rm.open_resource(visa_resource_addr)
        print("Connected to:", scope.query("*IDN?").strip())

        # Save image to scope
        scope.write(f'SAVE:IMAGe "{temp_on_scope}"')
        scope.query("*OPC?")  # wait for save

        # Read image from scope memory
        scope.write(f'FILESystem:READFile "{temp_on_scope}"')
        img_data = scope.read_raw(1024 * 1024)  # Read up to 1MB

        # Save locally
        with open(screenshot_path, "wb") as f:
            f.write(img_data)

        # Clean up image on scope
        scope.write(f'FILESystem:DELEte "{temp_on_scope}"')

        print(f"Screenshot saved to: {screenshot_path}")
    except Exception as e:
        print(f"Oscilloscope screenshot failed: {e}")
    finally:
        try:
            scope.close()
            rm.close()
        except:
            pass

    return screenshot_path

from data_utils import generate_filename
from oscilloscope_utils import capture_oscilloscope_screenshot_pyvisa

# You already generate the CSV file path like this:
csv_file = generate_filename(device_name, temp, freq, volt, config, duty)

# Log your data...
# log_data_to_csv(csv_file, data)

# Capture oscilloscope screenshot in same folder with consistent filename
capture_oscilloscope_screenshot_pyvisa("TCPIP0::192.168.1.100::inst0::INSTR", csv_file)